### ISSUE TITLE
requires requests

### ISSUE THREAD

**Issue by Jeremy-Heer** [authlib/demo-oauth-client#1]
The flask-google-login example requires the requests module.
Otherwise:
env\lib\site-packages\authlib\integrations\_client\oauth_registry.py", line 49, in use_oauth_clients
    clients = self.AVAILABLE_CLIENTS[name]
KeyError: 'requests'

to resolve this:
pip install requests

**Comment by lepture** [comment]
Added in readme

**Comment by prafullamohadikar** [comment]
> The flask-google-login example requires the requests module.
> Otherwise:
> env\lib\site-packages\authlib\integrations_client\oauth_registry.py", line 49, in use_oauth_clients
> clients = self.AVAILABLE_CLIENTS[name]
> KeyError: 'requests'
> 
> to resolve this:
> pip install requests

I already have requests
