### ISSUE TITLE
Flask example using google auth isn't parsing id_token

### ISSUE THREAD

**Issue by grosscol** [authlib/demo-oauth-client#20]
Using authlib 1.0.0rc1 and running the demo code.
I am running into an the issue where the id_token is in the response, but is not being parsed.  I suspect this and issue #17 might be related.

The userinfo is not being added to the token, so the following returns `None`.
https://github.com/authlib/demo-oauth-client/blob/f9eb5cb65f1907c977b902f6385c89b79c816791/flask-google-login/app.py#L36

Calling `oauth.google.parse_id_token(token, None)` to manually get `userinfo` is my current workaround.

I suspect that the state query param is not getting picked up here:
https://github.com/lepture/authlib/blob/169c7dcfc47478c8d55553cc95fb0f5578162b77/authlib/integrations/flask_client/apps.py#L100

**Comment by lepture** [comment]
check the master code.
