### ISSUE TITLE
Starlette Oauth logout not removing user

### ISSUE THREAD

**Issue by rmblau** [authlib/demo-oauth-client#22]
Hello, 

I am using the starlette Google login demo, slightly modified for my use case, and I notice that when I use the logout function it doesn't properly clear the user from the browser cache and instead will log me back into the previously signed into account. I have no idea how to fix this presently. Any guidance would be appreciated. Thank you in advance.

**Comment by alikemalagirman** [comment]
I have the same issue...

**Comment by lepture** [comment]
https://developers.google.com/identity/protocols/oauth2/web-server#httprest

Please check this commit: https://github.com/authlib/demo-oauth-client/commit/e9c8aa1c9d05da32c8ca0a740b6475c78b53e6c6
