### ISSUE TITLE
Is it a demo for facebook?

### ISSUE THREAD

**Issue by arthuravila26** [authlib/demo-oauth-client#5]
I'm after a demo for facebook. Can't reach a way to make the oauth.register for facebook. I've tried to adapt the Twitter one for facebook and including the App ID and App Secret, but when redirect to the facebook login page, I get a "Invalid App ID".

**Comment by gupta-shrinath** [comment]
You can check this pull request https://github.com/authlib/demo-oauth-client/pull/8
